### ISSUE TITLE
SchemaFactory

### ISSUE THREAD

**Issue by Big-Shark** [thecodingmachine/graphqlite-bundle#18]
@moufmouf Why we don't use SchemaFactory in the bundle?
Now we have a problem, with commit [31003db986caf16502eac60fa5f2c49992b8c2a2](https://github.com/thecodingmachine/graphqlite-bundle/commit/31003db986caf16502eac60fa5f2c49992b8c2a2), because FieldMiddlewarePipe does not supported argument.

I see 3 ways now
1) change __constructor
```
/**
     * Initializes the queue.
     * @param FieldMiddlewareInterface[] $middlewares
     */
    public function __construct(iterable $middlewares)
    {
        $this->pipeline = new SplQueue();
        foreach ($middlewares as $middleware) {
            $this->pipe($middleware);
        }
    }
```
2) Change graphqlite.xml and use [calls](https://symfony.com/doc/current/service_container/calls.html)
3) Use SchemaFactory in bundle.

@moufmouf please, write to me, what do you think about it.

**Comment by moufmouf** [comment]
> Now we have a problem, with commit 31003db986caf16502eac60fa5f2c49992b8c2a2, because FieldMiddlewarePipe does not supported argument.

Ok, I ackowledge the problem here.

Using `SchemaFactory` would certainly make the bundle easier to use and to maintain.

That being said, we would loose some flexibility (like the ability to decorate services declared in the bundle). Let me think just a bit more about it.

In the meantime, I'll work on some integration tests to catch this kind of errors in the future.

**Comment by moufmouf** [comment]
@Big-Shark 

After careful thought, I think you are right.
Using the SchemaFactory in the bundle removes a ton of code, some duplicated code and will help globally to move faster and with less bug.

Thanks for tip!
